name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-16.04
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags
        
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install Auto
        run: |
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v9.33.2/auto-linux.gz | gunzip > ~/auto;
          chmod a+x ~/auto;

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          bundler install;
          ~/auto shipit;
